<?php
namespace app\modules\system\controllers;

use app\controllers\BaseController;
use app\models\system\TbcuitmoonDictionary;
use app\models\TbcuitmoonUser;
use common\commonFuc;
use Yii;
use yii\filters\AccessControl;

class UserController extends BaseController{



    public $enableCsrfValidation=false;


//    public function behaviors()
//    {
////        return parent::behaviors(); // TODO: Change the autogenerated stub
//        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'only' => ['index','create', 'get-create', 'get-role'],
//                'rules' => [
//                    [
//                        'allow' => true,
//                        'actions' => ['index','get-create', 'get-role'],
//                        'roles' => ['?'],
//                    ],
//                ],
//            ],
//        ];
//    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $m_user = new TbcuitmoonUser();
        $m_dic = new TbcuitmoonDictionary();
        $com = new commonFuc();

        $list = $m_user->find()->select(['CuitMoon_UserName','CuitMoon_UserID','CuitMoon_UserRealName','CuitMoon_UserZipCode','CuitMoon_UserWorkingStatus']);
        $countList = clone $list;

        $pages = $com->Tab($countList);
        return $this->render('index',[
            'pages' => $pages,
            'list' => $list->limit($pages->limit)->offset($pages->offset)->all(),
            'course' => $m_dic->getDictionaryList('课程'),
        ]);
    }


    public function actionCreate()
    {
        $m_user = new TbcuitmoonUser();
        $com = new commonFuc();
        $post = Yii::$app->request->post();
        if ($m_user->load($post)) {
            $m_user->CuitMoon_UserPassWord = Yii::$app->security->generatePasswordHash($m_user->CuitMoon_UserPassWord);
            $m_user->CuitMoon_UserID = $com->create_id();
            $m_user->CuitMoon_AreaCode = $com->nameTranCode($post['TbcuitmoonUser']['CuitMoon_AreaCode']);
            if ($m_user->validate() && $m_user->save()) {
                $com->JsonSuccess('添加成功');
            } else {
                $com->JsonFail($m_user->getErrors());
            }
        }else{
            $com->JsonFail('数据出错');
        }
    }


    public function actionGetRole()
    {
        $auth = Yii::$app->authManager;

        $id = Yii::$app->request->get('id');
        $Roles = $auth->getRoles();
        $Role = $auth->getRolesByUser($id);
        $Data['Choice'] = $Role;
        $Data['All'] = $Roles;
        echo json_encode($Data);
    }

    public function actionCreateRole()
    {
        $auth = Yii::$app->authManager;
        $com = new commonFuc();

        $info = Yii::$app->request->post();
        $auth->revokeAll($info['id']);
        $Role = $auth->getRole($info['role']);
        $auth->assign($Role,$info['id']);
        $com->JsonSuccess('修改成功');
    }

    public function actionDelete()
    {
        if(\Yii::$app->request->isGet)
        {
            $get = \Yii::$app->request->get();
            if(isset($get['ids']))
            {
                foreach ($get['ids'] as $key => $value) {
                    $auth = Yii::$app->authManager;
                    $auth->revokeAll($value);
                    TbcuitmoonUser::deleteAll(['CuitMoon_UserID'=>$value]);
                }
                echo "删除成功";
            }
            else
                echo "删除失败";
        }
    }
    public function actionView()
    {
        if(\Yii::$app->request->isGet)
        {
            $get = \Yii::$app->request->get();
            if(isset($get['id']))
                echo json_encode(TbcuitmoonUser::find()->where(['CuitMoon_UserID'=>$get['id']])->asArray()->one());
        }
    }

    public function actionUpdate()
    {
         if(\Yii::$app->request->isPost)
        {
            $post = \Yii::$app->request->post();
            if(isset($post['TbcuitmoonUser']['CuitMoon_UserID']))
            {
                $aim = TbcuitmoonUser::find()->where(['CuitMoon_UserID'=>$post['TbcuitmoonUser']['CuitMoon_UserID']])->one();
                if($aim && $aim->load($post) &&$aim->save())
                    echo "修改成功";
                else
                    echo $aim->getErrors();
            }
            else
                echo "修改失败";
        }
    }
    public function actionResetPasswd()
    {
        if(\Yii::$app->request->isPost)
        {
            $post = \Yii::$app->request->post();
            if(isset($post['ID']))
            {

                $aim = TbcuitmoonUser::find()->where(['CuitMoon_UserID'=>$post['ID']])->one();
                $aim['CuitMoon_UserPassWord'] = Yii::$app->security->generatePasswordHash($aim->CuitMoon_UserName);

                if($aim->save())
                    echo "密码已重置为老师ID";

                else
                    echo "重置失败";
            }
        }
    }

}